Repository GreepTheSheep/openplanet-MXRandom, pull requests merged in 2023-06, with the labels that each got.

#78 fix: remove length parameters
  src/Settings/SearchingParameters.as
  src/Utils/MX/Methods/LoadRandomMap.as
  src/Utils/RMC/GlobalProperties.as
Labels: enhancement, Randomizer

#77 feat: allow map name/map pack/map author filtering for maps
  src/Settings/SearchingParameters.as
  src/Utils/MX/Methods/LoadRandomMap.as
Labels: enhancement, Randomizer

#82 fix: fix issue caused by incorrect handle assignment
  src/Utils/MX/Methods/LoadRandomMap.as
  src/Utils/RMC/GlobalProperties.as
Labels: enhancement, Mode: RMT

#84 refactor(UI): put stronger emphasis on the invalidity of a run
  src/Settings/SearchingParameters.as
  src/Utils/RMC/RMC.as
Labels: enhancement, Mode: RMC

#86 Add ability to proxy trackmania api to another url
  src/Exports/ExportsCode.as
  src/Interface/Renders/RecentlyMapsList.as
  src/Settings/About.as
  src/Settings/RMCParameters.as
  src/Utils/MX/Methods/DownloadMap.as
  src/Utils/MX/Methods/FetchMapTags.as
  src/Utils/MX/Methods/LoadRandomMap.as
  src/Utils/Migration.as
Labels: enhancement, Randomizer

#87 feat: check for exact map author
  src/Settings/SearchingParameters.as
  src/Utils/MX/Methods/LoadRandomMap.as
Labels: enhancement, Randomizer

#90 Fix null pointer exception with player best times
  src/Utils/RMC/RMT.as
Labels: bug, TMNEXT, Mode: RMT, Extension: MLHook/MLFeed
